version: "3.1"
services:

  mongo:
    image: mongo:4.0.6-xenial
    volumes:
      - ${database_dir}:/data/db
    environment:
      - "AUTH=yes"
      - "MONGO_INITDB_ROOT_USERNAME=${db_admin_username}"
      - "MONGO_INITDB_ROOT_PASSWORD=${db_admin_password}"
      - "MONGO_INITDB_DATABASE=${cryptocurrency}"
    ports:
      - 127.0.0.1:${db_port}:27017

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 127.0.0.1:${mongo_web_admin_port}:8081
    environment:
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=${db_admin_username}"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=${db_admin_password}"
      - "ME_CONFIG_MONGODB_SERVER=${db_host}"
      - "ME_CONFIG_MONGODB_AUTH_DATABASE=${cryptocurrency}"

  block-engine:
    build:
      context: .
    depends_on:
      - mongo
    network_mode: "host"
    environment:
      - "MONGODB_ADMIN_USER=${db_admin_username}"
      - "MONGODB_ADMIN_PASS=${db_admin_password}"
      - "MONGODB_READONLY_USER=${db_readonly_username}"
      - "MONGODB_READONLY_PASS=${db_readonly_password}"
      - "MONGODB_PORT=${db_port}"
      - "CRYPTO=${cryptocurrency}"
      - "CRYPTO_USER=${cryptocurrency_rpc_username}"
      - "CRYPTO_PASS=${cryptocurrency_rpc_password}"
      - "CRYPTO_PORT=${cryptocurrency_rpc_port}"
      - "CRYPTO_HOST=zcashd"
      - "TX_ADDRESS_CACHE_LIMIT=${tx_address_cache_limit}"
